### ISSUE TITLE
Enable the ability to attach objects to the running context like Node REPL does.

### ISSUE THREAD

**Issue by edwinclement08** [11ways/janeway#17]
So here is the idea, Node's REPL gives a context object which can be pre-loaded with whatever objects/libraries is needed in the specific project.
Here is the documentation for the same. https://nodejs.org/api/repl.html#repl_global_and_local_scope

This would be amazing.

Use Cases:
```
// Loading in common data manipulation libraries
const R = require('ramda');
replServer.context.R = R;

// Add in non-caching Require call
replServer.context.cleanRequire = (name) => {
  delete require.cache[require.resolve(name)];
  // eslint-disable-next-line global-require
  return require(name);
};
// 
```

I checked out the `lib/init.js`, but it seems a bit out of reach. If you could give me a general walk through the codebase, I would be glad to make this PR.

**Comment by skerit** [comment]
@edwinclement08 That's actually something Janeway provides too. Though I used the `vm_context` property name :)

So you could do something like this:

```js
__Janeway.vm_context.my_repl_property = 1;
```

and now that's available to you:

![janeway_repl_property](https://user-images.githubusercontent.com/755212/96891238-c0578100-1488-11eb-9604-25ddd30d6600.png)

Is that enough information to help you out? Just shout if you need any more information :)

**Comment by edwinclement08** [comment]
Hey, This is exactly what I needed. Thanks a lot. 
Janeway is a great upgrade from the REPL I was using. 
Thanks for this amazing tool.

**Comment by skerit** [comment]
You're welcome! Glad it can be of use :)
